ToDoApp/urls.py
from django.contrib import admin
from django.urls import path , include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ToDoModule.urls'))
]

ToDoModule/urls.py
from django.urls import path 
from . import views

app_name = 'ToDoModule'
urlpatterns = [
    path('', views.index , name="index"),
    path('store' , views.storeData , name='storeData'),
    path('deleta_all' , views.deleteAll , name="deleteAll"),
    path('deleteSelected' , views.deleteSelected , name="deleteSelected" ),
    path('delete/<int:id>' , views.delete , name='delete'),
    path('update/<int:id>' , views.update , name='update')
]

ToDoModule/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.

class ToDoModule(models.Model):
    text = models.CharField(max_length=250)
    pub_date = models.DateTimeField('date published')
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    def __str__(self):
        return self.text

ToDoModule/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import ToDoModule
import datetime
from django.shortcuts import redirect

# Create your views here.

def index(request):
    dataStored = request.session.get('dataStored')
    if dataStored == True :
        data = {'status' : 'true' , 'message' : 'Data is Stored Sucessfully'}
    elif dataStored == False :
        data = { 'status': request.session.get('dataStored') , 'message' : 'Something went wrong'}
    else:
        data = None

    listData = ToDoModule.objects.all()
    context = {'listData' : listData}
    return render(request, 'TodoModule/index.html' , context)

def storeData(request):
    text = request.POST['text']
    now = datetime.datetime.now()
    data = ToDoModule(text=text , pub_date=now)
    if data.save():
        request.session['dataStored'] = True
    return redirect('/')
    
def deleteAll(request):
    ToDoModule.objects.all().delete()
    return redirect('/')

def deleteSelected(request):
    if 'ids[]' in (dict(request.POST)) :
        ids = (dict(request.POST)["ids[]"])
        ToDoModule.objects.filter(id__in=(ids)).delete() # query
    return redirect('/')

def delete(request , id):
    ToDoModule.objects.get(id=id).delete()
    return redirect('/')

def update(request , id):
    text = ToDoModule.objects.get(id=id)
    text.text = request.POST['text']
    text.save()
    return redirect('/')

ToDoModule/templates/ToDoModule/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
     <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> 

    <meta charset="utf-8">

<style>
    /* Basic Style */

body {
	background: #fff;
	color: #333;
	font-family: Lato, sans-serif;
	background-color:#e4e4e4;
}

.container {
	display: block;
	width: 400px;
	margin: 10px auto 100px;
	background-color:#fff;
	padding:0px 10px 10px 10px;
	border-radius:10px
}

h2 {
	text-align:center;
	padding-top:10px;
	margin-bottom:0px;
}

ul {
	margin: 0;
	padding: 0;
}

li * {
	float: left;
}

li,
h3 {
	clear: both;
	list-style: none;
}

input,
button {
	outline: none;
}

button {
	background: none;
	border: 0px;
	color: #888;
	font-size: 15px;
	width: 60px;
	margin: 10px 0 0;
	font-family: Lato, sans-serif;
	cursor: pointer;
}

button:hover {
	color: #333;
}


/* Heading */

h3,
label[for='new-task'] {
	color: #333;
	font-weight: 700;
	font-size: 15px;
	border-bottom: 2px solid #333;
	padding: 20px 0 10px;
	margin: 0;
	text-transform: uppercase;
}

input[type="text"] {
	margin: 0;
	font-size: 18px;
	line-height: 18px;
	height: 18px;
	padding: 10px;
	border: 1px solid #ddd;
	background: #fff;
	border-radius: 6px;
	font-family: Lato, sans-serif;
	color: #888;
}

input[type="text"]:focus {
	color: #333;
}


/* New Task */

label[for='new-task'] {
	display: block;
	margin: 0 0 20px;
}

input#new-task {
	float: left;
	width: 318px;
}

p > button:hover {
	color: #0FC57C;
}


/* Task list */

li {
	overflow: hidden;
	padding: 20px 0;
	border-bottom: 1px solid #eee;
}

li > input[type="checkbox"] {
	margin: 0 10px;
	position: relative;
	top: 15px;
}

li > label {
	font-size: 18px;
	line-height: 40px;
	width: 237px;
	padding: 0 0 0 11px;
}

li > input[type="text"] {
	width: 226px;
}

li > .delete:hover {
	color: #CF2323;
}


/* Completed */

#completed-tasks label {
	text-decoration: line-through;
	color: #888;
}


/* Edit Task */



ul li.editMode input[type=text] {
	display: block;
}

 .hideForm {
	display: none;
}
</style>





  </head>
  <body>
	<div class="container">
        <div>{{ status }}</div>
		<h2>TODO LIST</h2>
		<h3>Add Item</h3>
		<p>
            <form method="post" action="{% url 'ToDoModule:storeData'  %}">
                {% csrf_token %}
                <div class="form-group">
                  <label for="textfield">Text:</label>
                  <input name="text" type="text" class="form-control" id="textfield">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form> 

		</p>

        <h3>Todo <a href="{% url 'ToDoModule:deleteAll' %}" class="pull-right btn-sm btn-danger">Delete All</a> 
        </h3>
        <form method="POST" action="{% url 'ToDoModule:deleteSelected' %}">
            {% csrf_token %}
            <button type="submit" class="btn-sm btn-danger">Delete Selected</button>
            <ul id="incomplete-tasks">
                {% for data in listData %}
                <li id="liElement">
                    <input type="checkbox" name="ids[]" value="{{ data.id }}">
					<label id="textLabel{{ data.id }}" class="textLabel">{{ data.text }}</label>
					<div class="hideForm" id="displayForm{{ data.id }}">
						<form method="post" action="{% url 'ToDoModule:update' data.id %}" >
							{% csrf_token %}
							<input type="text" name="text" value="{{ data.text }}">
							<button type="submit" class="btn-sm btn-info" >Update</button>
						</form>
					</div>
                    <span class="edit btn-sm btn-info" id="editButton{{ data.id }}" onclick="addEditClass('{{ data.id }}')" >Edit</span>
					
					<a href="{% url 'ToDoModule:delete' data.id %}" class="delete btn-sm btn-danger">Delete</a>
                </li>
                {% endfor %}
            </ul>
        </form>
	</div>
	<script>
		function addEditClass(id) {
			document.getElementById("liElement").classList.add("editMode");
			document.getElementById("editButton"+id).style.display = "none";
			document.getElementById("textLabel"+id).style.display = "none";
			document.getElementById("displayForm"+id).classList.remove('hideForm');
			document.getElementById("displayForm"+id).style.display = "block";
		}
	</script>
</body>
</html>